ARG VERSION
ARG PACKAGE_TYPE

FROM apache/apisix-base-${PACKAGE_TYPE}:${VERSION} AS apisix-base
FROM api7/fpm

ARG ITERATION
ARG PACKAGE_VERSION
ARG PACKAGE_TYPE
ARG ARTIFACT

ENV ITERATION=${ITERATION}
ENV PACKAGE_VERSION=${PACKAGE_VERSION}
ENV PACKAGE_TYPE=${PACKAGE_TYPE}
ENV ARTIFACT=${ARTIFACT}

COPY --from=apisix-base /usr/local/openresty /tmp/build/output/openresty
COPY --from=apisix-base /tmp/dist /tmp/dist
COPY --from=apisix-base /tmp/codename /tmp/codename
COPY package-apisix-base.sh /package-apisix-base.sh
COPY post-install-apisix-base.sh /post-install-apisix-base.sh
COPY usr /usr

RUN /package-apisix-base.sh